Added file_force to copy without check dest

diff --git a/grind.d/_files b/grind.d/_files
--- a/grind.d/_files
+++ b/grind.d/_files
@@ -3,32 +3,40 @@ SUBCOMMAND_DESC="Library for file definitions"
 SUBCOMMAND_HELP=$(cat <<EOH
 
 This API assumes as ORIGIN for files to be
-a diretory under GRIND_DEF_DIR called 'files'. 
+a diretory under GRIND_DEF_DIR called 'files'.
 The ORIGIN file name is a path to a file inside
 files, you do not need to give the full path.
 
 Functions:
 
-file ORIG DEST        Will copy the file from GRIND_DEF_DIR/files/ORIG 
-                      to DEST, if DEST doesn't exist. 
+file ORIG DEST        Will copy the file from GRIND_DEF_DIR/files/ORIG
+                      to DEST, if DEST doesn't exist.
 EOH
 )
 
 __FILES_DEF_DIR="${GRIND_DEF_DIR}/files"
 
-function _file_copy() {
-  local orig="${1}"
-  local dest="${2}"
-  log "checking if ${orig} exists first."
-  [[ -f "${orig}" ]] || error "Cannot find origin ${orig} file."
-  log "do_run copy for ${orig} to ${dest}"
-  do_run "cp ${orig} ${dest}"
+function _file_exists () {
+  local file="${1}"
+  log "checking if '${file}' exists first."
+  [[ -f "${file}" ]] || error "Cannot find origin ${file} file."
 }
 
+# Copy file only if does not exist at destination
 function file() {
   local orig="${1}"
   local dest="${2}"
   log "file: orig=${orig} dest=${dest}"
-  _file_copy "${__FILES_DEF_DIR}/${orig}" "${dest}"
+  _file_exists "${__FILES_DEF_DIR}/${orig}"
+  do_run "cp '${__FILES_DEF_DIR}/${orig}' '${dest}'"
     unless_file "${dest}"
+}
+
+# Copy file without worrying if it exists at destination
+function file_force() {
+  local orig="${1}"
+  local dest="${2}"
+  log "file_force: orig=${orig} dest=${dest}"
+  _file_exists "${__FILES_DEF_DIR}/${orig}"
+  run "cp -f '${__FILES_DEF_DIR}/${orig}' '${dest}'"
 }
