Function to easily clone from github

diff --git a/grind.d/_github b/grind.d/_github
--- a/grind.d/_github
+++ b/grind.d/_github
@@ -3,19 +3,22 @@ SUBCOMMAND_DESC="Library to interact with github"
 SUBCOMMAND_HELP=$(cat <<EOH
 Functions:
 
-github  PKG      apt_pkg "package_name"
-                  will install package_name unless
-                  it is already installed.
+github USER/REPO into: DIRECTORY      Will checkout USER/REPO from github into
+                                      DIRECTORY
+
 EOH
 )
 
-GITHUB_URL="https://github.com/"
+GITHUB_URL="https://github.com"
 
 function github() {
-  [[ -z ${1} ]] && error "Missing user/repository argument"
+  [[ -z ${1} || ! ${1} =~ / ]]       && error "Missing user/repository argument\n"
+  [[ -n ${2} && ! ${2} =~ ^into:$ ]] && error "Missing to: keyword\n"
+  [[ -d ${3} ]]                      || error "${3} must be a directory\n"
+
   local user_repo=(${1//\// })
   local repository="${GITHUB_URL}/${1}.git"
-  local target_dir="${PROJECTS_DIR}/${user_repo[1]}"
+  local target_dir="${3}/${user_repo[1]}"
 
   do_run "git clone ${repository} ${target_dir}"
     unless_dir "${target_dir}"
